#include "../../inc/Command.hpp"
#include "../../inc/Server.hpp"
#include <ctime>

string getCurrentTime() {
	time_t now = time(NULL);
	char buf[100];
	strftime(buf, sizeof(buf), "%H:%M:%S", localtime(&now));
	return string(buf);
}

string getCurrentDate() {
	time_t now = time(NULL);
	char buf[100];
	strftime(buf, sizeof(buf), "%d.%m.%Y", localtime(&now));
	return string(buf);
}

Bot::Bot(Server *server) : ACommand(server), facts() {
	facts.push_back("Did you know? Honey never spoils.");
	facts.push_back("Did you know? Honey never spoils.");
	facts.push_back("Bananas are berries, but strawberries are not.");
	facts.push_back("Humans share about 60% of their DNA with bananas.");
	facts.push_back("Octopuses have three hearts!");
	facts.push_back("A day on Venus is longer than a year on Venus.");
	facts.push_back("There are more stars in the universe than grains of sand on Earth.");
	facts.push_back("Your nose and ears never stop growing.");
	facts.push_back("The Eiffel Tower can be 15 cm taller during the summer due to heat expansion.");
	facts.push_back("Sloths can hold their breath longer than dolphins, up to 40 minutes!");
	facts.push_back("Cows have best friends and can become stressed when they’re separated.");
	facts.push_back("A group of flamingos is called a 'flamboyance'.");
	facts.push_back("Wombat poop is cube-shaped.");
	facts.push_back("Banging your head against a wall burns 150 calories an hour.");
	facts.push_back("The shortest war in history was between Britain and Zanzibar in 1896. It lasted just 38 minutes.");
	facts.push_back("Human thigh bones are stronger than concrete.");
	facts.push_back("Butterflies taste with their feet.");
	facts.push_back("Koalas sleep up to 22 hours a day.");
	facts.push_back("The inventor of the Pringles can is now buried in one.");
	facts.push_back("Sharks are older than trees. They have been around for about 400 million years.");
	facts.push_back("Sea otters hold hands when they sleep to keep from drifting apart.");
	facts.push_back("Polar bear fur is actually transparent, not white.");
	facts.push_back("In Switzerland, it is illegal to own just one guinea pig, as they are social animals.");
	facts.push_back("Snakes can help predict earthquakes.");
	facts.push_back("Hot water freezes faster than cold water, known as the Mpemba effect.");
	facts.push_back("Rabbits can see behind them without moving their heads.");
	facts.push_back("A jiffy is an actual unit of time. It's 1/100th of a second.");
	facts.push_back("Ants never sleep, and they don’t have lungs.");
	facts.push_back("A bolt of lightning contains enough energy to toast 100,000 slices of bread.");
	facts.push_back("Humans and giraffes have the same number of neck vertebrae—seven.");
	facts.push_back("The heart of a blue whale is so large, a human could swim through its arteries.");
	facts.push_back("Scotland’s national animal is the unicorn.");
	facts.push_back("A cockroach can live for weeks without its head due to its open circulatory system.");
	facts.push_back("A chef’s hat traditionally has 100 folds, representing the 100 ways to cook an egg.");
	facts.push_back("Pineapple is a natural meat tenderizer.");
	facts.push_back("A snail can sleep for up to three years.");
	facts.push_back("The largest snowflake ever recorded was 15 inches wide.");
	facts.push_back("An eagle can kill a young deer and fly away with it.");
	facts.push_back("Dogs have a unique nose print, similar to human fingerprints.");
	facts.push_back("Alaska is the only U.S. state that can be typed on one row of a keyboard.");
	facts.push_back("The moon has moonquakes, similar to earthquakes on Earth.");
	facts.push_back("Crocodiles cannot stick out their tongues.");
	facts.push_back("Most of the dust in your home is made up of dead skin cells.");
	facts.push_back("The average person will spend six months of their life waiting for red lights to turn green.");
	facts.push_back("Cats can’t taste sweetness.");
	facts.push_back("Tigers’ skin is striped, not just their fur.");
	facts.push_back("Venus is the only planet in the solar system that rotates clockwise.");
	facts.push_back("The inventor of the frisbee was turned into a frisbee after he died.");
	facts.push_back("Starfish have no brain and no blood.");
	facts.push_back("If you lift a kangaroo’s tail off the ground, it can’t hop.");
	facts.push_back("There’s a species of jellyfish that is biologically immortal.");
	facts.push_back("Apples float in water because they are 25% air.");
	facts.push_back("A group of pugs is called a 'grumble'.");
	facts.push_back("A single strand of spider silk is thinner than a human hair but five times stronger than steel.");
	facts.push_back("Owls don’t have eyeballs. They have eye tubes.");
	facts.push_back("The scientific term for brain freeze is 'sphenopalatine ganglioneuralgia'.");
	facts.push_back("Mantis shrimps can see circular polarized light, a rare ability in the animal kingdom.");
	facts.push_back("Goosebumps are a survival mechanism from when humans had more body hair, which would stand up to make us look more intimidating.");
	facts.push_back("It rains diamonds on Saturn and Jupiter.");
	facts.push_back("Lobsters have blue blood due to the presence of copper.");
	facts.push_back("The longest hiccuping spree lasted 68 years.");
	facts.push_back("The first computer was invented in the 1940s and was the size of a room.");
	facts.push_back("An ostrich’s eye is bigger than its brain.");
	facts.push_back("Jellyfish have been around for more than 500 million years, even before dinosaurs.");
	facts.push_back("Bamboo can grow up to 35 inches in a single day.");
	facts.push_back("The dot over the letter 'i' is called a 'tittle'.");
	facts.push_back("Horses and cows sleep standing up but can only dream lying down.");
	facts.push_back("The world's oldest toy is a stick.");
	facts.push_back("There is an island in the Bahamas inhabited only by swimming pigs.");
	facts.push_back("Elephants are the only animals that can't jump.");
	facts.push_back("A jiffy is the time it takes for light to travel one centimeter in a vacuum.");
	facts.push_back("Octopuses have blue blood because they use copper-based molecules to carry oxygen.");
	facts.push_back("The longest recorded flight of a chicken was 13 seconds.");
	facts.push_back("A crocodile cannot stick its tongue out, as it’s attached to the roof of its mouth.");
	facts.push_back("Cleopatra lived closer in time to the first moon landing than to the construction of the Great Pyramid of Giza.");
	facts.push_back("There are more public libraries in the U.S. than there are McDonald’s.");
	facts.push_back("The shortest commercial flight in the world lasts just 57 seconds. It runs between two islands in Scotland.");
	facts.push_back("If you keep a goldfish in a dark room, it will eventually turn white.");
	facts.push_back("Dragonflies have six legs but cannot walk.");
	facts.push_back("An octopus has nine brains—one for each arm and one central brain.");
	facts.push_back("There are more trees on Earth than stars in the Milky Way galaxy.");
	facts.push_back("The human nose can remember 50,000 different scents.");
	facts.push_back("You’re more likely to get a computer virus from visiting religious sites than adult websites.");
	facts.push_back("Snails have 14,000 teeth, located on their tongues!");
	facts.push_back("Mosquitoes are attracted to people who have recently eaten bananas.");
	facts.push_back("A group of owls is called a 'parliament'.");
	facts.push_back("If you cut a starfish, it can regenerate its limbs and potentially even grow into new starfish.");
	facts.push_back("Sharks are the only fish that can blink with both eyes.");
	facts.push_back("In Japan, there are more pets than children.");
	facts.push_back("A single teaspoon of honey represents the lifetime work of 12 bees.");
	facts.push_back("Humans are the only animals known to blush.");
	facts.push_back("Rats and mice laugh when tickled.");
	facts.push_back("The first oranges weren’t orange; they were green.");
	facts.push_back("Rabbits and parrots can see behind themselves without moving their heads.");
	facts.push_back("It’s impossible to hum while holding your nose.");
	facts.push_back("The world’s oldest known piece of chewing gum is over 9,000 years old.");
	facts.push_back("Koalas have fingerprints that are almost indistinguishable from human fingerprints.");
	facts.push_back("The dot on a dice is called a 'pip'.");
	facts.push_back("A hippo’s sweat is pink!");
	facts.push_back("Bees sometimes sting other bees.");
	facts.push_back("The inventor of the microwave appliance only received $2 for his discovery.");
	facts.push_back("The can opener was invented 48 years after the can.");
	facts.push_back("Dolphins have names for each other and can recognize their own names.");
	facts.push_back("If you sneeze too hard, you could fracture a rib.");
	facts.push_back("Butterflies drink from mud puddles to get nutrients.");
	facts.push_back("Water can boil and freeze at the same time under the right conditions, called the 'triple point'.");
	facts.push_back("The average cloud weighs over a million pounds.");
	facts.push_back("The name for the shape of Pringles is called a 'hyperbolic paraboloid'.");
	facts.push_back("Venus is the hottest planet in our solar system, even though Mercury is closer to the Sun.");
	facts.push_back("Earth is the only planet in our solar system not named after a god.");
	facts.push_back("The heart of a shrimp is located in its head.");
	facts.push_back("Sea cucumbers can eject their internal organs to scare off predators.");
	facts.push_back("Pigeons can do math at a similar level to some primates.");
	facts.push_back("Humans and giraffes both have seven vertebrae in their necks.");
	facts.push_back("Blue whales are so massive, their heart can be heard from over two miles away underwater.");
	facts.push_back("The first known recipe was for beer.");
	facts.push_back("Beavers have transparent eyelids to see underwater while swimming.");
	facts.push_back("Oranges were originally green in warmer regions.");
	facts.push_back("On Saturn’s moon Titan, lakes and rivers are filled with liquid methane.");
	facts.push_back("Astronauts can grow up to two inches taller in space due to the lack of gravity.");
	facts.push_back("There are more than 200 corpses of climbers on Mount Everest, which are used as waypoints.");
	facts.push_back("Banging your head against a wall burns 150 calories an hour.");
	facts.push_back("Cows have best friends and can become stressed if they are separated.");
	facts.push_back("Hummingbirds are the only birds that can fly backward.");
	facts.push_back("The world's largest desert is Antarctica.");
	facts.push_back("A group of flamingos is called a 'flamboyance'.");
	facts.push_back("Tigers have striped skin, not just striped fur.");
	facts.push_back("A snail can sleep for three years at a time.");
	facts.push_back("Honeybees can recognize human faces.");
	facts.push_back("The inventor of the frisbee was turned into a frisbee after he died.");
	facts.push_back("Wombat poop is cube-shaped.");
	facts.push_back("A group of ferrets is called a 'business'.");
	facts.push_back("Elephants are the only mammals that can’t jump.");
	facts.push_back("Peanuts aren’t nuts; they’re legumes.");
	facts.push_back("A jiffy is an actual unit of time; it’s 1/100th of a second.");
	facts.push_back("A flock of crows is known as a 'murder'.");
	facts.push_back("The unicorn is the national animal of Scotland.");
	facts.push_back("A day on Venus is longer than a year on Venus.");
	facts.push_back("The longest time between two twins being born is 87 days.");
	facts.push_back("Banging your head against a wall for one hour burns 150 calories.");
	facts.push_back("Scotland’s national animal is the unicorn.");
	facts.push_back("Squirrels are responsible for planting thousands of trees each year by forgetting where they buried their nuts.");
	facts.push_back("The fingerprints of a koala are so similar to humans that they can taint crime scenes.");
	facts.push_back("In Switzerland, it is illegal to own just one guinea pig because they get lonely.");
	facts.push_back("A 10-gallon hat will only hold ¾ of a gallon of liquid.");
	facts.push_back("Sloths can hold their breath longer than dolphins can.");
	facts.push_back("The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.");
	facts.push_back("In 2006, a Coca-Cola employee offered to sell Coca-Cola secrets to Pepsi. Pepsi reported them to Coca-Cola.");
	facts.push_back("Kangaroos can’t walk backward.");
	facts.push_back("A group of pugs is called a 'grumble'.");
	facts.push_back("The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo'.");
	facts.push_back("Octopuses can change color and texture to blend in with their surroundings.");
	facts.push_back("The average person walks the equivalent of five times around the world in their lifetime.");
	facts.push_back("The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.");
	facts.push_back("Some cats are allergic to humans.");
	facts.push_back("A bear's sense of smell is more than seven times better than a bloodhound's.");
	facts.push_back("You can't hum while holding your nose.");
	facts.push_back("The longest place name in the world is 85 letters long: Taumatawhakatangihangakoauauotamateapokaiwhenuakitanatahu.");
	facts.push_back("A group of jellyfish is called a 'smack'.");
	facts.push_back("The most expensive pizza in the world costs $12,000 and takes 72 hours to make.");
	facts.push_back("Avocados are toxic to birds.");
	facts.push_back("The heart of a blue whale is so big that a small child could swim through its arteries.");
	facts.push_back("Elephants can recognize themselves in a mirror, showing signs of self-awareness.");
	facts.push_back("Sharks have been around longer than trees.");
	facts.push_back("Butterflies taste with their feet.");
	facts.push_back("A group of owls is called a 'parliament'.");
	facts.push_back("Cheetahs can’t roar, but they can meow like house cats.");
	facts.push_back("Sea otters hold hands when they sleep to keep from drifting apart.");
	facts.push_back("There are more stars in the universe than grains of sand on all the Earth's beaches.");
	facts.push_back("A day on Mercury lasts 176 Earth days.");
	facts.push_back("A goldfish's memory span is three seconds. (This is actually a myth; they can remember for months!)");
	facts.push_back("Humans are the only animals that blush.");
	facts.push_back("A jiffy is the time it takes for light to travel one centimeter in a vacuum.");
	facts.push_back("It takes eight minutes and twenty seconds for light from the Sun to reach Earth.");
	facts.push_back("A cloud can weigh over a million pounds.");
	facts.push_back("The longest wedding veil was longer than 63 football fields.");
	facts.push_back("A sneeze travels about 100 miles per hour.");
	facts.push_back("Bananas are curved because they grow towards the sun.");
	facts.push_back("Some cats are allergic to humans.");
	facts.push_back("The world's oldest known breed of domesticated dog is the Saluki.");
	facts.push_back("A jiffy is an actual unit of time; it’s 1/100th of a second.");
	facts.push_back("The world's largest snowflake on record was 15 inches wide.");
	facts.push_back("Humans and giraffes have the same number of neck vertebrae.");
	facts.push_back("Frogs can freeze without dying.");
	facts.push_back("The average human body carries about 60,000 miles of blood vessels.");
	facts.push_back("The dot over the letters 'i' and 'j' is called a tittle.");
	facts.push_back("Scorpions can glow under ultraviolet light.");
	facts.push_back("The longest word in the English language is 189,819 letters long. It's the chemical name for the protein Titin.");
	facts.push_back("A small child could swim through the veins of a blue whale.");
	facts.push_back("Ketchup was sold in the 1830s as medicine.");
	facts.push_back("Some mushrooms can create their own wind to help disperse their spores.");
	facts.push_back("In Japan, there is a train station that has no entrance or exit, it's only for the view.");
	facts.push_back("You can’t fold a paper in half more than seven times.");
	facts.push_back("The smell of freshly cut grass is actually a plant distress signal.");
	facts.push_back("Avocados are classified as a fruit, specifically a berry.");
	facts.push_back("A group of crows is called a 'murder'.");
	facts.push_back("A single strand of spaghetti is called a 'spaghetto'.");
	facts.push_back("A shrimp's heart is located in its head.");
	facts.push_back("The most commonly forgotten item for travelers is a toothbrush.");
	facts.push_back("A crocodile cannot stick its tongue out.");
	facts.push_back("Some cats can’t digest lactose, despite popular belief.");
	facts.push_back("The average person spends six months of their lifetime waiting for red lights to turn green.");
	facts.push_back("The world's largest desert is Antarctica.");
	facts.push_back("A bee can fly at a speed of 15 miles per hour.");
	facts.push_back("A jiffy is often used in computing to refer to 1/100th of a second.");
	facts.push_back("The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of the metal.");
	facts.push_back("Tigers have striped skin, not just striped fur.");
	facts.push_back("Sloths can hold their breath longer than dolphins can.");
	facts.push_back("The human nose can detect over 1 trillion scents.");
	facts.push_back("Polar bear skin is black and their fur is actually transparent.");
	facts.push_back("Dolphins have names for each other.");
	facts.push_back("Sharks have been around longer than trees.");
	facts.push_back("Wombat poop is cube-shaped.");
	facts.push_back("A snail can sleep for three years.");
	facts.push_back("The fingerprints of a koala are so similar to humans that they can taint crime scenes.");
	facts.push_back("Octopuses have blue blood and three hearts.");
	facts.push_back("A group of flamingos is called a 'flamboyance'.");
	facts.push_back("The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.");
	facts.push_back("Cats have fewer toes on their back paws.");
	facts.push_back("The inventor of the Frisbee was turned into a Frisbee after he died.");
	facts.push_back("It rains diamonds on Jupiter and Saturn.");
	facts.push_back("The world's largest snowman was 122 feet tall.");
	facts.push_back("A day on Venus is longer than a year on Venus.");
	facts.push_back("Sharks are the only fish that can blink with both eyes.");
	facts.push_back("Koalas sleep up to 22 hours a day.");
	facts.push_back("Horses and cows sleep standing up.");
	facts.push_back("A day on Earth is not exactly 24 hours, but 23 hours, 56 minutes, and 4 seconds.");
	facts.push_back("Butterflies can taste with their feet, and they also have taste receptors on their wings.");
	facts.push_back("Elephants are the only mammals that can't jump.");
	facts.push_back("There are over 7,500 varieties of apples grown in the world.");
	facts.push_back("The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo'.");
	facts.push_back("A jiffy is also used in physics to measure the time light takes to travel one centimeter in a vacuum.");
	facts.push_back("Birds are the closest living relatives to dinosaurs.");
	facts.push_back("The longest hiccup lasted for 68 years.");
	facts.push_back("Pineapples take about two years to grow.");
	facts.push_back("The average person walks the equivalent of five times around the world in their lifetime.");
	facts.push_back("A group of hedgehogs is called a 'array'.");
	facts.push_back("The largest living organism on Earth is a fungus in Oregon that spans over 2,385 acres.");
	facts.push_back("The dot over the letters 'i' and 'j' is called a tittle.");
	facts.push_back("A group of ferrets is called a 'business'.");
	facts.push_back("Honey never spoils; archeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still edible.");
	facts.push_back("The heart of a shrimp is located in its head.");
	facts.push_back("A group of pugs is called a 'grumble'.");
	facts.push_back("The world's largest desert is actually Antarctica.");
	facts.push_back("A jiffy is a unit of time in computing, commonly used to represent 1/100th of a second.");
	facts.push_back("The world's most expensive coffee is made from coffee beans digested by civet cats.");
	facts.push_back("A bolt of lightning is five times hotter than the surface of the sun.");
	facts.push_back("Wombats produce cube-shaped poop.");
	facts.push_back("The unicorn is the national animal of Scotland.");
	facts.push_back("A single strand of spaghetti is called a 'spaghetto'.");
	facts.push_back("There's a town in Norway called Hell.");
	facts.push_back("Bananas are berries, but strawberries are not.");
	facts.push_back("The majority of your brain is fat.");
	facts.push_back("Humans are the only animals that blush.");
	facts.push_back("A jellyfish is 95% water.");
	facts.push_back("An octopus has three hearts and blue blood.");
	facts.push_back("The shortest war in history lasted 38 minutes.");
	facts.push_back("The first computer was invented in the 1940s and took up an entire room.");
	facts.push_back("Dolphins have been observed using tools.");
	facts.push_back("More people are killed by cows each year than by sharks.");
	facts.push_back("A crocodile cannot stick its tongue out.");
	facts.push_back("A group of crows is called a 'murder'.");
	facts.push_back("Sharks can detect one drop of blood in an Olympic-sized swimming pool.");
	facts.push_back("A snail can sleep for up to three years.");
	facts.push_back("The average person produces enough saliva in their lifetime to fill two swimming pools.");
	facts.push_back("The largest recorded snowflake was 15 inches wide.");
	facts.push_back("Tigers have striped skin, not just striped fur.");
	facts.push_back("The fingerprints of a koala are so similar to humans that they can taint crime scenes.");
	facts.push_back("A 'pounce' is the name for a group of cats.");
	facts.push_back("A bolt of lightning contains enough energy to toast 100,000 slices of bread.");
	facts.push_back("Kangaroos can't walk backward.");
	facts.push_back("The average person will spend six months of their lifetime waiting for red lights to turn green.");
	facts.push_back("The first product to have a barcode was Wrigley’s chewing gum.");
	facts.push_back("The Mona Lisa has no eyebrows.");
	facts.push_back("A lion's roar can be heard from five miles away.");
	facts.push_back("The world’s smallest reptile was discovered in 2021, a chameleon that measures just 13.5 mm.");
	facts.push_back("There are more stars in the universe than grains of sand on all the world's beaches.");
	facts.push_back("A day on Mercury is longer than a year on Mercury.");
	facts.push_back("A 'jiffy' is a real unit of time, used in computer science to refer to 10 milliseconds.");
	facts.push_back("Butterflies can taste with their feet.");
	facts.push_back("There are more than 1,000 different species of fruit flies.");
	facts.push_back("The oldest known living tree is over 4,800 years old.");
	facts.push_back("Sea otters hold hands while sleeping to keep from drifting apart.");
	facts.push_back("The longest time between two twins being born is 87 days.");
	facts.push_back("The fingerprints of a koala are so similar to humans that they can taint crime scenes.");
	facts.push_back("Some cats are allergic to humans.");
	facts.push_back("A group of owls is called a 'parliament'.");
	facts.push_back("A group of flamingos is called a 'flamboyance'.");
	facts.push_back("The longest hiccuping spree lasted 68 years.");
	facts.push_back("Cows have best friends and get stressed when they are separated.");
	facts.push_back("A day on Venus is longer than a year on Venus.");
	facts.push_back("Octopuses have three hearts and blue blood.");
	facts.push_back("In Switzerland, it is illegal to own just one guinea pig because they are social animals.");
	facts.push_back("Polar bear skin is black, and their fur is transparent, reflecting light.");
	facts.push_back("The tongue of a blue whale can weigh as much as an elephant.");
	facts.push_back("Dolphins have names for each other, and they can call out to one another.");
	facts.push_back("Cheetahs can accelerate from 0 to 60 mph in just three seconds.");
	facts.push_back("The inventor of the frisbee was turned into a frisbee after he died.");
	facts.push_back("Peanuts are not nuts; they are legumes.");
	facts.push_back("A group of jellyfish is called a 'smack'.");
	facts.push_back("Hummingbirds are the only birds that can fly backward.");
	facts.push_back("Sloths can hold their breath longer than dolphins can.");
	facts.push_back("The shortest commercial flight in the world is only 57 seconds long.");
	facts.push_back("The world's largest snowman was built in Maine and was over 122 feet tall.");
	facts.push_back("A shark is the only fish that can blink with both eyes.");
	facts.push_back("The world's smallest mammal is the bumblebee bat, which weighs less than a penny.");
	facts.push_back("A group of hedgehogs is called a 'prickle'.");
	facts.push_back("Cats have over 20 muscles that control their ears.");
	facts.push_back("The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion of the metal.");
	facts.push_back("Ants can lift objects 50 times their body weight.");
	facts.push_back("The longest wedding veil was longer than 23 football fields.");
	facts.push_back("Humans are the only animals that shed emotional tears.");
	facts.push_back("It takes eight minutes and twenty seconds for sunlight to reach the Earth.");
	facts.push_back("A baby octopus is the size of a pea when it's born.");
	facts.push_back("Rabbits can see behind them without turning their heads.");
	facts.push_back("Sharks are older than trees; they have been around for over 400 million years.");
	facts.push_back("The average person walks the equivalent of three times around the world in their lifetime.");
	facts.push_back("The heart of a blue whale is so large that a human could swim through its arteries.");
	facts.push_back("Cows can remember and recognize individual faces for years.");
	facts.push_back("A snail can sleep for up to three years.");
	facts.push_back("Wombat poop is cube-shaped.");
	facts.push_back("The world’s largest desert is Antarctica.");
	facts.push_back("The longest recorded flight of a chicken is 13 seconds.");
	facts.push_back("In Japan, there is a train station that has no entrance or exit; it's just for tourists to take pictures.");
	facts.push_back("The inventor of the Pringles can is buried in one.");
	facts.push_back("A duck’s quack doesn’t echo, and no one knows why.");
	facts.push_back("In Switzerland, it's illegal to own just one guinea pig because they get lonely.");
	facts.push_back("Some cats are allergic to humans—talk about a twist!");
	facts.push_back("In South Korea, there are more than 50 different types of kimchi, and they even have a National Kimchi Day!");
	facts.push_back("Cows have best friends and can become stressed when they are separated. So, no cow should ever be alone!");
	facts.push_back("A crocodile cannot stick its tongue out; it’s just too busy snapping up lunch!");
	facts.push_back("Wombat poop is cube-shaped, which is the ultimate form of solid waste management.");
	facts.push_back("The average person will spend six months of their life waiting for red lights to turn green, just like waiting for a bus that never comes.");
	facts.push_back("Bananas are berries, but strawberries are not. If that doesn’t make you question everything you know about fruit, I don’t know what will!");
	facts.push_back("Kangaroos can't walk backward, which is probably why they always look forward to hopping around!");
	facts.push_back("It's physically impossible for pigs to look up at the sky—unless they’re rolling in the mud and staring into the heavens!");
	facts.push_back("The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo'. So, thank you, Dr. Seuss, for giving nerds their name!");
	facts.push_back("A group of flamingos is called a 'flamboyance'. That's right, even birds know how to flaunt their stuff!");
	facts.push_back("You can’t hum while holding your nose closed. Go ahead, I dare you!");
	facts.push_back("In the UK, it is illegal to handle a salmon in suspicious circumstances. No salmon shenanigans here!");
	facts.push_back("A jiffy is the time it takes for light to travel one centimeter in a vacuum. So when someone says, 'I’ll be back in a jiffy,' they might just be running a physics experiment!");
	facts.push_back("Butterflies taste with their feet, which must make for some really interesting food choices!");
	facts.push_back("If you lift a kangaroo's tail off the ground, it can't hop. That’s why they’re always hopping around with their tails on the ground!");
	facts.push_back("The world's oldest known pet was a 38-year-old macaw named Charlie who lived to be 114!");
	facts.push_back("You can lead a cow upstairs, but you can’t lead it down. Talk about a one-way ticket!");
	facts.push_back("An octopus has three hearts, but they still can’t seem to find one that loves them back.");
	facts.push_back("The average human body contains enough fat to make seven bars of soap. So, if you ever run out, you know where to look!");
	facts.push_back("In ancient Egypt, servants were smeared with honey to attract flies away from the pharaoh. Talk about a sticky situation!");
	facts.push_back("Humans shed about 600,000 particles of skin every hour—so technically, you’re always leaving a little piece of yourself everywhere you go!");
	facts.push_back("In the 1800s, a popular method for treating depression was to drill a hole in your skull. This is called trepanation, and it probably didn't help anyone's mood!");
	facts.push_back("The average person will eat eight spiders while sleeping in their lifetime—sweet dreams indeed!");
	facts.push_back("A single teaspoon of honey represents the life’s work of about 12 bees. So next time you’re sweetening your tea, remember the little workers who sacrificed for your sugar fix.");
	facts.push_back("There are more fake flamingos in the world than real ones. Nature just can’t compete with yard decor!");
	facts.push_back("Dead people can get goosebumps—so if you’re feeling chilly, it could be more than just a draft!");
	facts.push_back("The word 'mortuary' comes from the Latin word 'mors', which means 'death'. It’s like they were trying to tell you what you’re walking into!");
	facts.push_back("In some parts of Italy, it's considered good luck to touch a dead body. I’m not sure who came up with that idea, but they must have had a wild sense of fortune!");
	facts.push_back("In Japan, there is a 'Crying Sumo' contest where wrestlers compete to see who can make a baby cry first. It’s a traditional practice, but also a good reminder: babies will cry over anything!");
	facts.push_back("A goldfish has a memory span of about three seconds. If only humans could forget their troubles as quickly!");
	facts.push_back("The most commonly used letter in the English language is E, but the least used letter is Q. Looks like Q just can’t catch a break!");
	facts.push_back("If you put a raisin in a glass of champagne, it will keep floating to the top and sinking to the bottom. It’s basically the world's most dramatic swimmer!");
	facts.push_back("There’s a type of jellyfish that is immortal. It can revert to its juvenile form after maturing, meaning it’s got an endless loop on life. Talk about a cheat code!");
	facts.push_back("In medieval times, people believed that the tooth fairy was actually a mouse. I guess a mouse seemed less terrifying than a tiny being sneaking under your pillow!");
	facts.push_back("Did you know? The average human body contains enough bones to make an entire skeleton.");
	facts.push_back("When you die, the last sense to go is usually hearing. So, you might hear everyone arguing over your will.");
	facts.push_back("Human teeth are as strong as shark teeth. But remember, humans usually get arrested if they use them in the same way.");
	facts.push_back("If you’re buried after death, your body will decompose within a few decades. Cremation is just a faster version of the process.");
	facts.push_back("A single human can produce enough bones in their lifetime to fill a small charnel house. It’s recycling, but for the macabre.");
	facts.push_back("Crows hold grudges and can recognize human faces. Be nice, or risk an ominous crow jury above your window.");
	facts.push_back("Butterflies drink blood if given the chance. They’re pretty, but they're basically winged vampires.");
	facts.push_back("Tarantulas can survive for years without food. So, if they’re watching you, they might just be waiting.");
	facts.push_back("Banging your head against a wall burns 150 calories an hour. It’s not a recommended exercise, though it might explain some of humanity’s decisions.");
	facts.push_back("Male seahorses give birth. So, the next time someone complains about being tired, show them a seahorse dad.");
	facts.push_back("Lobsters don’t age in the traditional sense, but they do keep growing until something (usually dinner) stops them.");
	facts.push_back("Octopuses are masters of escape and can fit through tiny gaps. If you think you’ve trapped them, you’re probably wrong.");
	facts.push_back("The average mattress doubles in weight over 10 years due to dust mites and their droppings. Sweet dreams!");
	facts.push_back("In some traditions, 'catacombs' meant resting peacefully forever. Today, they’re mostly cool Instagram spots.");
	facts.push_back("The inventor of the guillotine was beheaded by his own invention. Talk about poetic justice.");
	facts.push_back("If you put a frog in boiling water, it jumps out. But if you heat it slowly, it stays. Just like people in bad relationships.");
	facts.push_back("When you blush, the lining of your stomach blushes too. A fun fact for the next time you embarrass yourself.");
	facts.push_back("Sloths can hold their breath longer than dolphins, but mainly because they move so slowly it hardly matters.");
	facts.push_back("When humans first started farming, some used skulls as planters. Early farm-to-table was hardcore.");
	facts.push_back("When you see the light at the end of the tunnel, remember: it might just be the oncoming train.");
	facts.push_back("Pigs can eat an entire human body, bones and all. Now that's the start of an interesting farm story.");
	facts.push_back("Human flesh supposedly tastes like pork, hence the term 'long pig'—just in case you wanted a nightmare snack thought.");
	facts.push_back("Spiders can crawl into your mouth while you sleep, but the good news is, it’s extremely rare. Probably.");
	facts.push_back("If you die alone with a pet, they might eat you out of hunger. It’s not betrayal; it’s a survival instinct.");
	facts.push_back("When you yawn, someone somewhere else yawns too. And it might be Death getting ready.");
	facts.push_back("A large percentage of murders go unsolved. Sweet dreams.");
	facts.push_back("Ants can carry many times their own weight. This means, technically, they can carry a piece of you too.");
	facts.push_back("Koalas have fingerprints so similar to humans that they could contaminate a crime scene. Murder koala, anyone?");
	facts.push_back("Cats bring you dead animals as gifts, or as a subtle reminder that you're next if they wanted.");
	facts.push_back("In some places, bodies are used as tourist attractions. Catacombs, anyone?");
	facts.push_back("There’s a species of jellyfish that is biologically immortal. Meanwhile, we struggle with our morning coffee.");
	facts.push_back("Flamingos filter their food through their beaks and swallow with their heads upside down. But they’re still more graceful than you at 3 a.m.");
	facts.push_back("The oldest known 'your mom' joke is over 3,500 years old. Humanity has always had a thing for dark humor.");
	facts.push_back("Crocodiles don’t die of old age; they just keep growing until nature, injury, or a bigger predator ends them.");
	facts.push_back("Astronauts in space can’t cry properly due to zero gravity—tears just pool up around their eyes. Sounds fun, right?");
	facts.push_back("Sharks have been around longer than trees, but they haven’t evolved Wi-Fi. That’s kind of sad for them.");
	facts.push_back("Parrots can live over 60 years. They’ll repeat your embarrassing secrets long after you're gone.");
	facts.push_back("Most people are dead longer than they are alive. Make good use of your time above ground.");
	facts.push_back("Your skeleton renews itself every 10 years. So, you’re never more than a decade away from being a whole new pile of bones.");
	facts.push_back("Octopuses taste with their arms. So when they grab you, you’re technically a tasting platter.");
	facts.push_back("There are more tigers in captivity than in the wild. Not the most comforting thought for the next zoo visit.");
	facts.push_back("Human skin is replaced every 2-4 weeks, leaving a trail of dead cells. In essence, you’re always shedding your old self.");
	facts.push_back("Scorpions can hold their breath for up to six days. Take that as you will.");
	facts.push_back("Owls can turn their heads 270 degrees. So, it’s hard to sneak up on them. Keep that in mind if they’re plotting.");
	facts.push_back("The average adult has 206 bones. Not all of them will make it to the end.");
	facts.push_back("When you die, your hair and nails don’t actually keep growing. Your skin just shrinks, making it look that way. Surprise!");
	facts.push_back("The human brain can remain conscious for a few minutes after decapitation. Gives a whole new meaning to 'losing your head.'");
	facts.push_back("The oldest known prosthetic is a wooden toe from ancient Egypt. Sometimes losing a part of you means gaining a story.");
	facts.push_back("In some cultures, people are buried with bells attached to their coffins. You know, just in case.");
	facts.push_back("Drowning doesn’t look like drowning on TV. It’s quiet, quick, and hard to notice—like life’s unfortunate surprises.");
	facts.push_back("Human eyes stay roughly the same size from birth, while everything else grows. So those baby eyes just stay hauntingly big.");
	facts.push_back("There’s a cemetery in France where bodies decompose above ground in stone chambers. Talk about high-rise apartments.");
	facts.push_back("When lightning strikes the ground, it can fuse the soil into glass. Nature’s accidental glassblowing.");
	facts.push_back("The last meal of many astronauts before launch includes steak and eggs, a tradition from when pilots needed 'solid food.' It’s a meal fit for both space and the morgue.");
	facts.push_back("There’s a species of fish that swims up the urinary tract of animals. Swimming and privacy don’t mix.");
	facts.push_back("Some people used to believe that photographs stole a part of your soul. You’ll be surprised how many people still believe it.");
	facts.push_back("Around 2 million people die each year from workplace accidents. The job market really is that competitive.");
	facts.push_back("During WWII, Japanese soldiers would often carry grenades to avoid capture, making it a bad time to try making friends.");
	facts.push_back("If you have a pacemaker, you can’t be cremated due to the risk of explosion. It’s a high-stakes way to end up in ashes.");
	facts.push_back("Some corals use tentacles to sting and eat other corals. Even the ocean has its ‘friendly neighbors.’");
	facts.push_back("In ancient Rome, the same pool was used to wash clothes and urinate. On the bright side, laundry day was never boring.");
	facts.push_back("There’s a parasite that enters a fish’s mouth, eats its tongue, and replaces it. It lives rent-free in the mouth—literally.");
	facts.push_back("The 'suicide plant' of Australia has tiny hairs that can cause pain for months or even years. Australia really doesn’t hold back.");
	facts.push_back("There’s a mental phenomenon called the 'death grin' that happens when people die from hanging. Muscles contract in a way that makes them smile.");
	facts.push_back("Coffins used to have viewing windows. Because what’s creepier than staring at your loved one trapped in a glass box?");
	facts.push_back("Human decomposition releases over 400 chemicals. So when you’re gone, your last gift to the world is...chemical pollution.");
	facts.push_back("If your body was left in a coffin long enough, it would eventually turn into a soap-like substance called 'grave wax.'");
	facts.push_back("When bodies decompose in water, they form a layer of blubber. Imagine your final contribution being... buoyant.");
	facts.push_back("A common cause of death during autopsies? Handling scalpels. Irony at its sharpest.");
	facts.push_back("At some point in history, 'coffin birth' happened—a dead pregnant body could expel the fetus due to gas build-up. A disturbing farewell.");
	facts.push_back("Bats can carry more than 60 different viruses dangerous to humans. They may be small, but they pack quite the viral punch.");
	facts.push_back("There’s a plant called the corpse flower, and it smells just like death. The bloom lasts only a day, perfect for nature’s most dramatic performance.");
	facts.push_back("Cannibalism has been practiced throughout history. In times of desperation, the food pyramid takes a strange new shape.");
	facts.push_back("The RMS Titanic is still being eaten by bacteria, slowly disintegrating it on the ocean floor. Even in death, it’s not alone.");
	facts.push_back("A body left in the desert can be mummified by the heat, giving you a shot at immortality you didn’t ask for.");
	facts.push_back("A person sheds 40 pounds of skin in a lifetime. Congratulations! You’re constantly leaving tiny bits of yourself everywhere.");
	facts.push_back("The deadliest animal in the world is the mosquito. They’re tiny, but they’ve killed more humans than any other creature.");
	facts.push_back("Black boxes on planes aren’t actually black—they’re bright orange for easy recovery. Just one of those small details for your final flight.");
	facts.push_back("Astronauts’ suits are so pressurized that they actually expand, making it nearly impossible for them to bend over. Nothing says ‘space hero’ like being unable to tie your own shoes.");
	facts.push_back("Ancient Romans used crushed mouse brains as toothpaste. Looks like ‘natural’ toothpaste has been around a lot longer than we thought.");
	facts.push_back("In the 1800s, people used mummies as fuel for locomotives in Egypt. Turns out, mummies burn pretty well.");
	facts.push_back("In the Victorian era, it was common to take photos of dead family members as if they were alive. Some even posed them sitting up. A final family portrait, if you will.");
	facts.push_back("‘Executioner’s sword’ was a real job title. Swing once, retire rich (if a bit haunted).");
	facts.push_back("Hearing loss is one of the last senses to fade before death. So, those who go quietly may still be listening.");
	facts.push_back("Newborn babies don’t shed tears until they’re a few months old. Their first cries are dry, as if life is waiting to fully show its cards.");
	facts.push_back("There’s a ‘Catacombs Festival’ in Paris where people party among the bones. It’s the city of love and... skeletal remains.");
	facts.push_back("There’s a jellyfish that can biologically reverse its age, effectively making it immortal. Meanwhile, humans are still trying to figure out aging cream.");
	facts.push_back("Sea cucumbers can eject their internal organs to escape predators. It’s like an emergency escape button... for your insides.");
	facts.push_back("Spiders actually ‘dance’ when they mate. It’s a performance that usually ends in one of them becoming dinner.");
	facts.push_back("The deepest part of the ocean is home to bizarre creatures with glowing eyes and transparent bodies. They’ll never see the light, but they’ll see you.");
	facts.push_back("In 16th century Europe, it was believed that a corpse’s hair and nails kept growing. Turns out, just the corpse’s reputation grew.");
	facts.push_back("A 'safety coffin' was once patented with a tube for air and a bell to signal if someone was buried alive. You know, just in case.");
	facts.push_back("When bodies decompose, they can move due to gas build-up. There’s a chance the dead aren’t resting as peacefully as we think.");
	facts.push_back("The human heart can beat outside the body, as long as it has an oxygen supply. Love truly is unstoppable.");
	facts.push_back("Cats can detect death and often curl up next to terminally ill patients. A dark but comforting companion till the end.");
	facts.push_back("Butterflies are cannibals when food is scarce. Those beautiful wings have a sinister side.");
	facts.push_back("Killer whales have been observed teaching each other to hunt humans. So, maybe skip the ocean swim in certain areas.");
	facts.push_back("Orangutans have been observed making tools to fish. Soon, they might take our jobs too.");
	facts.push_back("There are viruses out there that turn insects into zombies, forcing them to spread the infection. The real zombie apocalypse has just been miniaturized.");
	facts.push_back("Crows will hold a ‘funeral’ if one of their group dies. They’re mourning… or plotting.");
	facts.push_back("Lobsters don’t die from old age, but instead keep growing until something else kills them. The ocean’s eternal problem-solvers.");
	facts.push_back("Most laugh tracks on TV were recorded decades ago, meaning the laughs you hear are often from people who are now dead.");
	facts.push_back("Koalas have fingerprints that are nearly identical to humans, which can be a problem at crime scenes. Watch out, we might have some furry felons out there.");
	facts.push_back("The term 'saved by the bell' is rumored to come from people being buried alive. They’d tie a string to a bell to ring if they woke up underground.");

}

Bot::~Bot() {}

void Bot::exec(Client *client, vector<string> &token)
{
	if (client->GetClientStatus() < LOGIN)
	{
		client->MsgToClient(ERR_NOTREGISTERED(client->GetNickname()));
		return ;
	}
	if (token.size() > 1 && token[1] == "HELLO")
		client->MsgToClient("Hi, i'm bot, How u doin today?");
	else if (token.size() >	1 && token[1] == "WEATHER") {
		srand(time(0));
		int randomValue = rand() % 2;

		if (randomValue == 0) {
			client->MsgToClient("Hello from Kocaeli! The clouds are heavy, it's a chilly 10°C, and we've got quite a wind—blowing strong at 50 km/h!");
			client->MsgToClient(PRINT_ASCII_ART());
		} else {
			client->MsgToClient("Hey server, reporting in from Kocaeli! The sky is cloaked in clouds, it's a cozy 22°C, and there's a gentle 12 km/h breeze in the air.");
			client->MsgToClient(PRINT_ASCII_ART2());
		}
	}
	else if (token.size() > 1 && token[1] == "TIME")
		client->MsgToClient("Current time is " + getCurrentTime());
	else if (token.size() > 1 && token[1] == "DATE")
		client->MsgToClient("Current date is " + getCurrentDate());
	else if (token.size() > 1 && token[1] == "FACT") {
		int randomIndex = rand() % facts.size();
		client->MsgToClient("Here's a fun fact for you: " + facts[randomIndex]);
	}
	else
		client->MsgToClient("I'm bot, i have these command: HELLO, WEATHER, TIME, DATE, FACT");
}
